services:
  api-gob:
    build:
      context: api-gob
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: "no"
  api-sqlite:
    build:
      context: api-sqlite
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    restart: "no"
